# Generated by Django 3.1.6 on 2021-03-17 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_corto', models.CharField(max_length=3, unique=True)),
                ('cupo_max', models.PositiveSmallIntegerField(verbose_name='Cupo máximo de personas')),
                ('descripcion', models.TextField(blank=True, default='', max_length=200)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'actividades',
                'ordering': ['nombre', 'cupo_max'],
            },
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('seleccionable', models.BooleanField(default=True)),
                ('cupo_actual', models.SmallIntegerField(default=0, editable=False)),
                ('cupo_max', models.SmallIntegerField(default=37, editable=False)),
                ('actividad', models.ForeignKey(limit_choices_to={'disponible': True}, on_delete=django.db.models.deletion.CASCADE, to='turno.actividad')),
                ('usuario', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'is_staff': False}, to=settings.AUTH_USER_MODEL, verbose_name='usuarios en este turno')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'db_table': 'turnos',
                'ordering': ['actividad', 'horario'],
                'unique_together': {('actividad', 'horario', 'fecha')},
            },
        ),
    ]
