# Generated by Django 3.1.6 on 2021-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_corto',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
    ]
