# Generated by Django 3.1.6 on 2021-03-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_auto_20210317_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='seleccionable',
            new_name='disponible',
        ),
    ]
