# Generated by Django 3.1.6 on 2021-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_actividad_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre_corto',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
