# Generated by Django 3.1.6 on 2021-03-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_auto_20210317_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cupo_actual',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='cupo_max',
        ),
    ]
