# Generated by Django 3.1.6 on 2021-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_auto_20210317_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
