# Generated by Django 3.1.6 on 2021-03-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0006_remove_turno_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
