# Generated by Django 3.1.6 on 2021-03-18 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0007_turno_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cupo_actual',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('actividad', 'horario', 'fecha')},
        ),
    ]
