# Generated by Django 3.1.6 on 2021-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0008_auto_20210318_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
    ]
