# Generated by Django 3.1 on 2021-02-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_usuario')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
